Repository OCA/margin-analysis, pull requests merged in 2020-07, with the labels that each got.

#72 [MIG][13.0] account_invoice_margin: Migration to v13.0
  account_invoice_margin/README.rst
  account_invoice_margin/__init__.py
  account_invoice_margin/__manifest__.py
  account_invoice_margin/i18n/account_invoice_margin.pot
  account_invoice_margin/i18n/es.po
  account_invoice_margin/i18n/fr.po
  account_invoice_margin/models/__init__.py
  account_invoice_margin/models/account_invoice.py
  account_invoice_margin/readme/CONTRIBUTORS.rst
  account_invoice_margin/readme/DESCRIPTION.rst
  account_invoice_margin/readme/USAGE.rst
  account_invoice_margin/report/__init__.py
  account_invoice_margin/report/account_invoice_report.py
  account_invoice_margin/security/account_invoice_margin_security.xml
  account_invoice_margin/static/description/account_invoice_form.png
  account_invoice_margin/static/description/account_invoice_form_tree.png
  account_invoice_margin/static/description/icon.png
  account_invoice_margin/static/description/index.html
  account_invoice_margin/tests/__init__.py
  account_invoice_margin/tests/test_account_invoice_margin.py
  account_invoice_margin/views/account_invoice_margin_view.xml
  setup/account_invoice_margin/odoo/addons/account_invoice_margin
  setup/account_invoice_margin/setup.py
Labels: bot is merging ⏳

#73 [MIG][13.0] sale_margin_delivered: Migration to v13.0
  sale_margin_delivered/README.rst
  sale_margin_delivered/__init__.py
  sale_margin_delivered/__manifest__.py
  sale_margin_delivered/i18n/es.po
  sale_margin_delivered/i18n/sale_margin_delivered.pot
  sale_margin_delivered/models/__init__.py
  sale_margin_delivered/models/sale_margin.py
  sale_margin_delivered/readme/CONFIGURE.rst
  sale_margin_delivered/readme/CONTRIBUTORS.rst
  sale_margin_delivered/readme/DESCRIPTION.rst
  sale_margin_delivered/readme/USAGE.rst
  sale_margin_delivered/reports/__init__.py
  sale_margin_delivered/reports/sale_report.py
  sale_margin_delivered/static/description/icon.png
  sale_margin_delivered/static/description/index.html
  sale_margin_delivered/tests/__init__.py
  sale_margin_delivered/tests/test_sale_margin_delivered.py
  sale_margin_delivered/views/sale_margin_delivered_view.xml
  setup/sale_margin_delivered/odoo/addons/sale_margin_delivered
  setup/sale_margin_delivered/setup.py
Labels: approved, bot is merging ⏳

#77 [FIX] sale_margin_security: onchange product
  sale_margin_security/__init__.py
  sale_margin_security/models/__init__.py
  sale_margin_security/models/sale_order.py
Labels: bot is merging ⏳

#70 [MIG][12.0] product_standard_margin (from 8.0)
  product_standard_margin/README.rst
  product_standard_margin/__init__.py
  product_standard_margin/__manifest__.py
  product_standard_margin/i18n/fr.po
  product_standard_margin/i18n/nl.po
  product_standard_margin/models/__init__.py
  product_standard_margin/models/product_product.py
  product_standard_margin/models/product_template.py
  product_standard_margin/readme/CONTRIBUTORS.rst
  product_standard_margin/readme/DESCRIPTION.rst
  product_standard_margin/readme/ROADMAP.rst
  product_standard_margin/static/description/product_form.png
  product_standard_margin/tests/__init__.py
  product_standard_margin/tests/test_module.py
  product_standard_margin/views/view_product_product.xml
  product_standard_margin/views/view_product_template.xml
Labels: bot is merging ⏳, needs review
