Repository OCA/margin-analysis, pull requests merged in 2021-09, with the labels that each got.

#96 [ADD] (12.0) product_pricelist_margin - new module to preview prices and margins, depending on the pricelist
  product_pricelist_margin/README.rst
  product_pricelist_margin/__init__.py
  product_pricelist_margin/__manifest__.py
  product_pricelist_margin/demo/product_pricelist.xml
  product_pricelist_margin/demo/product_product.xml
  product_pricelist_margin/demo/res_groups.xml
  product_pricelist_margin/i18n/fr.po
  product_pricelist_margin/i18n/product_pricelist_margin.pot
  product_pricelist_margin/models/__init__.py
  product_pricelist_margin/models/product_product.py
  product_pricelist_margin/models/product_template.py
  product_pricelist_margin/readme/CONTRIBUTORS.rst
  product_pricelist_margin/readme/DESCRIPTION.rst
  product_pricelist_margin/readme/INSTALL.rst
  product_pricelist_margin/readme/USAGE.rst
  product_pricelist_margin/static/description/product_template_form.png
  product_pricelist_margin/static/description/with_module_web_tree_dynamic_colored_field.png
  product_pricelist_margin/static/description/wizard_preview_pricelist_margin_form.png
  product_pricelist_margin/tests/__init__.py
  product_pricelist_margin/tests/test_module.py
  product_pricelist_margin/views/view_product_template.xml
  product_pricelist_margin/wizards/__init__.py
  product_pricelist_margin/wizards/wizard_preview_pricelist_margin.py
  product_pricelist_margin/wizards/wizard_preview_pricelist_margin.xml
  product_pricelist_margin/wizards/wizard_preview_pricelist_margin_line.py
Labels: bot is merging ⏳

#109 [12.0][IMP] sale_margin_delivered: No compute margin delivered fields for no delivered lines
  sale_margin_delivered/__manifest__.py
  sale_margin_delivered/migrations/12.0.1.0.2/post-migration.py
  sale_margin_delivered/models/sale_margin.py
  sale_margin_delivered/tests/test_sale_margin_delivered.py
Labels: approved, ready to merge, bot is merging ⏳

#111 [11.0][IMP]account_invoice_margin: General margins in invoices
  account_invoice_margin/models/account_invoice.py
  account_invoice_margin/readme/CONTRIBUTORS.rst
  account_invoice_margin/views/account_invoice_margin_view.xml
Labels: approved, bot is merging ⏳

#110 [13.0][IMP] account_invoice_margin: Avoid error when trying to install module with database populated with many invoices
  account_invoice_margin/__init__.py
  account_invoice_margin/__manifest__.py
  account_invoice_margin/hooks.py
  account_invoice_margin/tests/test_account_invoice_margin.py
Labels: approved, ready to merge, bot is merging ⏳

#114 [14.0][IMP] account_invoice_margin: Avoid error when trying to install module with database populated with many invoices
  account_invoice_margin/__init__.py
  account_invoice_margin/__manifest__.py
  account_invoice_margin/hooks.py
  account_invoice_margin/tests/test_account_invoice_margin.py
Labels: approved, bot is merging ⏳
