Repository OCA/margin-analysis, pull requests merged in 2021-07, with the labels that each got.

#99 [12.0][IMP] sale_order_margin_percent: Add margin percent field in sales order line
  sale_order_margin_percent/i18n/es.po
  sale_order_margin_percent/i18n/sale_order_margin_percent.pot
  sale_order_margin_percent/models/sale_order_margin.py
  sale_order_margin_percent/tests/test_margin_percent.py
  sale_order_margin_percent/views/sale_order_margin_percent_view.xml
Labels: approved, bot is merging ⏳

#100 [13.0][IMP] sale_order_margin_percent: Add margin percent field in sales order line
  sale_order_margin_percent/README.rst
  sale_order_margin_percent/i18n/es.po
  sale_order_margin_percent/i18n/sale_order_margin_percent.pot
  sale_order_margin_percent/models/sale_order_margin.py
  sale_order_margin_percent/readme/CONTRIBUTORS.rst
  sale_order_margin_percent/static/description/index.html
  sale_order_margin_percent/tests/test_margin_percent.py
  sale_order_margin_percent/views/sale_order_margin_percent_view.xml
Labels: approved, bot is merging ⏳

#101 [12.0][FIX] sale_margin_delivered: Force company for SO in tests
  sale_margin_delivered/tests/test_sale_margin_delivered.py
Labels: bot is merging ⏳

#90 [14.0][MIG] account_invoice_margin: Migration to 14.0
  account_invoice_margin/README.rst
  account_invoice_margin/__init__.py
  account_invoice_margin/__manifest__.py
  account_invoice_margin/i18n/account_invoice_margin.pot
  account_invoice_margin/i18n/es.po
  account_invoice_margin/i18n/fr.po
  account_invoice_margin/models/__init__.py
  account_invoice_margin/models/account_invoice.py
  account_invoice_margin/readme/CONTRIBUTORS.rst
  account_invoice_margin/readme/DESCRIPTION.rst
  account_invoice_margin/readme/USAGE.rst
  account_invoice_margin/report/__init__.py
  account_invoice_margin/report/account_invoice_report.py
  account_invoice_margin/security/account_invoice_margin_security.xml
  account_invoice_margin/static/description/account_invoice_form.png
  account_invoice_margin/static/description/account_invoice_form_tree.png
  account_invoice_margin/static/description/icon.png
  account_invoice_margin/static/description/index.html
  account_invoice_margin/tests/__init__.py
  account_invoice_margin/tests/test_account_invoice_margin.py
  account_invoice_margin/views/account_invoice_margin_view.xml
  setup/account_invoice_margin/odoo/addons/account_invoice_margin
  setup/account_invoice_margin/setup.py
Labels: approved, bot is merging ⏳, ready to merge
