Repository OCA/margin-analysis, pull requests merged in 2022-11, with the labels that each got.

#144 [14.0][MIG] sale_margin_security: Migration to 14.0
  sale_margin_security/README.rst
  sale_margin_security/__init__.py
  sale_margin_security/__manifest__.py
  sale_margin_security/i18n/es.po
  sale_margin_security/i18n/sale_margin_security.pot
  sale_margin_security/readme/CONFIGURE.rst
  sale_margin_security/readme/CONTRIBUTORS.rst
  sale_margin_security/readme/DESCRIPTION.rst
  sale_margin_security/readme/USAGE.rst
  sale_margin_security/report/__init__.py
  sale_margin_security/report/sale_report.py
  sale_margin_security/security/sale_margin_security_security.xml
  sale_margin_security/static/description/icon.png
  sale_margin_security/static/description/index.html
  sale_margin_security/views/sale_margin_security_view.xml
  setup/sale_margin_security/odoo/addons/sale_margin_security
  setup/sale_margin_security/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#147 [15.0][MIG] sale_margin_security: Migration to 15.0
  sale_margin_security/README.rst
  sale_margin_security/__init__.py
  sale_margin_security/__manifest__.py
  sale_margin_security/i18n/es.po
  sale_margin_security/i18n/sale_margin_security.pot
  sale_margin_security/readme/CONFIGURE.rst
  sale_margin_security/readme/CONTRIBUTORS.rst
  sale_margin_security/readme/DESCRIPTION.rst
  sale_margin_security/readme/USAGE.rst
  sale_margin_security/report/__init__.py
  sale_margin_security/report/sale_report.py
  sale_margin_security/security/sale_margin_security_security.xml
  sale_margin_security/static/description/icon.png
  sale_margin_security/static/description/index.html
  sale_margin_security/views/sale_margin_security_view.xml
  setup/sale_margin_security/odoo/addons/sale_margin_security
  setup/sale_margin_security/setup.py
Labels: approved, bot is merging ⏳

#150 [13.0][FIX] sale_margin_delivered: non storable
  sale_margin_delivered/models/sale_margin.py
Labels: approved, bot is merging ⏳

#149 [15.0] [MIG] sale_margin_delivered: Migration to 15.0
  sale_margin_delivered/README.rst
  sale_margin_delivered/__init__.py
  sale_margin_delivered/__manifest__.py
  sale_margin_delivered/i18n/es.po
  sale_margin_delivered/i18n/sale_margin_delivered.pot
  sale_margin_delivered/models/__init__.py
  sale_margin_delivered/models/sale_margin.py
  sale_margin_delivered/readme/CONFIGURE.rst
  sale_margin_delivered/readme/CONTRIBUTORS.rst
  sale_margin_delivered/readme/DESCRIPTION.rst
  sale_margin_delivered/readme/USAGE.rst
  sale_margin_delivered/reports/__init__.py
  sale_margin_delivered/reports/sale_report.py
  sale_margin_delivered/static/description/icon.png
  sale_margin_delivered/static/description/index.html
  sale_margin_delivered/tests/__init__.py
  sale_margin_delivered/tests/test_sale_margin_delivered.py
  sale_margin_delivered/views/sale_margin_delivered_view.xml
  setup/sale_margin_delivered/odoo/addons/sale_margin_delivered
  setup/sale_margin_delivered/setup.py
Labels: approved, bot is merging ⏳

#130 [14.0] [IMP] `account_invoice_margin`: several small improvements
  account_invoice_margin/models/account_invoice.py
  account_invoice_margin/report/account_invoice_report.py
Labels: approved, bot is merging ⏳

#155 [15.0][MIG] sale_margin_sync: Migration to 15.0
  sale_margin_sync/README.rst
  sale_margin_sync/__init__.py
  sale_margin_sync/__manifest__.py
  sale_margin_sync/i18n/sale_margin_sync.pot
  sale_margin_sync/models/__init__.py
  sale_margin_sync/models/stock_valuation_layer.py
  sale_margin_sync/readme/CONTRIBUTORS.rst
  sale_margin_sync/readme/DESCRIPTION.rst
  sale_margin_sync/static/description/icon.png
  sale_margin_sync/static/description/index.html
  sale_margin_sync/tests/__init__.py
  sale_margin_sync/tests/test_sale_margin_sync.py
  setup/sale_margin_sync/odoo/addons/sale_margin_sync
  setup/sale_margin_sync/setup.py
Labels: needs review, approved, bot is merging ⏳
