Repository OCA/margin-analysis, pull requests merged in 2023-08, with the labels that each got.

#170 [15.0][FIX] product_standard_margin: WARNING Deprecated call to decim…
  product_standard_margin/models/product_product.py
  product_standard_margin/models/product_template.py
Labels: approved, bot is merging ⏳

#171 [14.0][IMP] account_invoice_margin: add margin_percent to Invoice Analysis
  account_invoice_margin/i18n/account_invoice_margin.pot
  account_invoice_margin/i18n/es.po
  account_invoice_margin/i18n/fr.po
  account_invoice_margin/report/account_invoice_report.py
Labels: bot is merging ⏳

#169 [16.0][MIG] product_margin_classification
  product_margin_classification/README.rst
  product_margin_classification/__init__.py
  product_margin_classification/__manifest__.py
  product_margin_classification/data/decimal_precision.xml
  product_margin_classification/demo/product_margin_classification.xml
  product_margin_classification/demo/product_product.xml
  product_margin_classification/demo/res_groups.xml
  product_margin_classification/i18n/es.po
  product_margin_classification/i18n/fr.po
  product_margin_classification/i18n/product_margin_classification.pot
  product_margin_classification/models/__init__.py
  product_margin_classification/models/product_margin_classification.py
  product_margin_classification/models/product_product.py
  product_margin_classification/models/product_template.py
  product_margin_classification/readme/CONFIGURE.rst
  product_margin_classification/readme/CONTRIBUTORS.rst
  product_margin_classification/readme/DESCRIPTION.rst
  product_margin_classification/readme/ROADMAP.rst
  product_margin_classification/readme/USAGE.rst
  product_margin_classification/security/ir.model.access.csv
  product_margin_classification/security/ir_rule.xml
  product_margin_classification/static/description/icon.png
  product_margin_classification/static/description/index.html
  product_margin_classification/static/description/margin_classification_form.png
  product_margin_classification/static/description/margin_classification_tree.png
  product_margin_classification/static/description/product_product_form.png
  product_margin_classification/static/description/product_product_tree_incorrect_price.png
  product_margin_classification/tests/__init__.py
  product_margin_classification/tests/test_product_margin_classification.py
  product_margin_classification/views/view_product_margin_classification.xml
  product_margin_classification/views/view_product_product.xml
  product_margin_classification/views/view_product_template.xml
  setup/product_margin_classification/odoo/addons/product_margin_classification
  setup/product_margin_classification/setup.py
Labels: approved, bot is merging ⏳

#181 [FIX] product_margin_classification : do not loose margin classification when creating new product.template.
  product_margin_classification/models/product_template.py
  product_margin_classification/tests/test_product_margin_classification.py
Labels: approved, ready to merge, bot is merging ⏳
