Repository OCA/margin-analysis, pull requests merged in 2024-04, with the labels that each got.

#193 [FIX] use lst_price for _compute_margin in product.product
  product_standard_margin/models/product_product.py
  product_standard_margin/tests/test_module.py
Labels: approved, bot is merging ⏳

#198 [IMP] sale_margin[_delivered]_security: depend on product_cost_security
  sale_margin_delivered_security/README.rst
  sale_margin_delivered_security/__init__.py
  sale_margin_delivered_security/__manifest__.py
  sale_margin_delivered_security/models/__init__.py
  sale_margin_delivered_security/models/sale_order.py
  sale_margin_delivered_security/static/description/index.html
  sale_margin_delivered_security/views/sale_margin_delivered_view.xml
  sale_margin_security/README.rst
  sale_margin_security/__manifest__.py
  sale_margin_security/migrations/16.0.3.0.0/pre-migrate.py
  sale_margin_security/models/sale_order.py
  sale_margin_security/readme/CONFIGURE.rst
  sale_margin_security/readme/CONTEXT.rst
  sale_margin_security/readme/CONTRIBUTORS.rst
  sale_margin_security/readme/DESCRIPTION.rst
  sale_margin_security/readme/INSTALL.rst
  sale_margin_security/readme/USAGE.rst
  sale_margin_security/report/sale_report.py
  sale_margin_security/security/sale_margin_security_security.xml
  sale_margin_security/static/description/index.html
  sale_margin_security/tests/__init__.py
  sale_margin_security/tests/test_sale_margin.py
  sale_margin_security/views/sale_margin_security_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#201 [14.0][FIX] account_invoice_margin: wrong default margin calculation
  account_invoice_margin/hooks.py
Labels: approved, ready to merge, bot is merging ⏳
