Repository OCA/margin-analysis, pull requests merged in 2024-06, with the labels that each got.

#212 [FIX] [16.0] sale_margin_delivered: Margin Delivered (%) help doesn't match reality
  sale_margin_delivered/i18n/es.po
  sale_margin_delivered/i18n/sale_margin_delivered.pot
  sale_margin_delivered/models/sale_margin.py
Labels: approved, bot is merging ⏳

#208 [16.0][FIX] sale_margin_delivered_security: Add security groups to right fi…
  sale_margin_delivered_security/models/__init__.py
  sale_margin_delivered_security/models/sale_order_line.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#215 [16.0] sale_margin_delivery: Store percentage value as into odoo
  sale_margin_delivered/__manifest__.py
  sale_margin_delivered/migrations/16.0.2.0.0/post-migration.py
  sale_margin_delivered/models/sale_margin.py
  sale_margin_delivered/static/description/index.html
  sale_margin_delivered/tests/test_sale_margin_delivered.py
  sale_margin_delivered/views/sale_margin_delivered_view.xml
  sale_margin_delivered_dropshipping/tests/test_sale_margin_delivered_dropship.py
Labels: needs review, approved, bot is merging ⏳
